### ISSUE TITLE
IP adapter plus model batch images Seems to have no effect

### ISSUE THREAD

**Issue by liangkun43** [cubiq/ComfyUI_IPAdapter_plus#17] opened 2023-09-27 08:13 UTC
![微信截图_20230927160616](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/ed9e9c0c-ce4c-4317-8976-c28171606939)
![微信截图_20230927160717](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/50bcd5c0-d306-4c74-8711-46badde19d84)
and ip-adapter-plus-face_sd15 model also like this

**Comment by liangkun43** [comment] 2023-09-27 08:16
![微信截图_20230927161433](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/2e3002fd-5842-4914-86d0-b7c1223cb37e)
ip-adapter_sd15 model results are correct

**Comment by cubiq** [comment] 2023-09-27 08:25
it actually has an impact. try to connect the guy image directly to the IPAdapter node (not through the image batch), you'll see that the result will be different. The "plus" is stronger and gets more from your images and the first one takes the precedence for some reason.

If you want one image to have a stronger influence create a batch of 3 images and repeat one of the images twice....

... or just wait a few minutes, I'm pushing an update that lets you give more weight to an image from a batch

**Comment by liangkun43** [comment] 2023-09-27 09:36
> it actually has an impact. try to connect the guy image directly to the IPAdapter node (not through the image batch), you'll see that the result will be different. The "plus" is stronger and gets more from your images and the first one takes the precedence for some reason.它确实有影响。尝试将 Guy 图像直接连接到 IPAdapter 节点（而不是通过图像批处理），您会看到结果会有所不同。 “加号”更强，可以从图像中获得更多信息，并且由于某种原因，第一个优先。
> 
> If you want one image to have a stronger influence create a batch of 3 images and repeat one of the images twice....如果您希望一张图像具有更强的影响力，请创建一批 3 张图像，并将其中一张图像重复两次......
> 
> ... or just wait a few minutes, I'm pushing an update that lets you give more weight to an image from a batch...或者稍等几分钟，我正在推送一项更新，让您可以为批次中的图像赋予更多权重

Thanks！because i get different resulr from another extension
![微信截图_20230927173439](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/4de3d054-b2bd-4b78-afae-28fdedc8b4dc)

**Comment by cubiq** [comment] 2023-09-27 09:53
can you send me the two reference images that you are using so I can check if I can get the same result. Thanks!

the two extension use mostly the same models, so they should have close results.

**Comment by liangkun43** [comment] 2023-09-27 10:00
![ComfyUI_00674_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/62860411-929c-40e6-bec2-9033d2e8a65d)
![SDXL_0 9_Output_00012_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/10597905-42dc-4dee-ade7-d6f733b1c078)

**Comment by liangkun43** [comment] 2023-09-27 10:05
They released a new model,I got some mistakes.
https://huggingface.co/h94/IP-Adapter/blob/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.bin
![微信截图_20230927180332](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/fd6f62eb-05ca-4013-95f4-ddeca2574234)

**Comment by cubiq** [comment] 2023-09-27 10:08
even if it's an SDXL model you have to use it with the SD1.5 image encoder (clipvision)

**Comment by liangkun43** [comment] 2023-09-27 10:16
yes, i use it with the SD1.5 image encoder.another ip-adapter_sdxl_vit-h model is working
![微信截图_20230927181636](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/a66f0ad6-76d4-402c-8843-c5a1965bcf0f)

**Comment by cubiq** [comment] 2023-09-27 10:27
can you update now to the latest version and see if the plus models work with image batches. I believe everything's fine now

![plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/66de562d-17f7-4ed6-a5a8-e49f960223c1)

**Comment by liangkun43** [comment] 2023-09-27 10:47
yes,thanks! but ip-adapter-plus_sdxl_vit-h model still receive same error

**Comment by cubiq** [comment] 2023-09-27 11:05
sorry I didn't see they released a new model. I'll check what the problem is.

I'm closing this issue as the original problem is solved. I opened this https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/18 with the new issue. It's an easy fix thanks for reporting it

**Closed by cubiq** 2023-09-27 11:05 UTC

**Comment by liangkun43** [comment] 2023-09-27 11:12
Thank you very much for your work
