### ISSUE TITLE
IPadapter Plus using signficantly more VRAM since latest ComfyUI Update

### ISSUE THREAD

**Issue by Inner-Reflections** [cubiq/ComfyUI_IPAdapter_plus#38] opened 2023-10-13 18:16 UTC
Hi I wanted to submit this. Finding significantly more VRAM usage since latest ComfyUI update (~4gb more vram on a image batch of 16).

**Comment by cubiq** [comment] 2023-10-13 18:21
can you find out to exactly what commit?

**Comment by melMass** [comment] 2023-10-14 00:25
I think this one https://github.com/comfyanonymous/ComfyUI/commit/1a4bd9e9a6fc2b364ebb547dbd80736548cf9f5c

**Comment by Inner-Reflections** [comment] 2023-10-14 00:37
It is defiantly one from yesterday Oct 12.

**Comment by Inner-Reflections** [comment] 2023-10-14 00:49
It is this one https://github.com/comfyanonymous/ComfyUI/commit/88733c997fd807a572d4a214d2c15fc5dd17b3c6

The one prior works as before this one does not

**Comment by cubiq** [comment] 2023-10-14 06:08
thanks for checking. can you try to disable xformers and see if that helps?

**Comment by cubiq** [comment] 2023-10-14 06:55
> 
> Edit: This is bizarre. Defiantly things are worse after that commit, however even on the one before it I can have two workflows that seem identical but one is over my vram limit the other is fine.

it would be important to understand when this actually started then

**Comment by Inner-Reflections** [comment] 2023-10-14 14:17
Hey Definatly a lot worse after that. I did try disabling xformers with no change.

**Comment by Inner-Reflections** [comment] 2023-10-14 14:18
Using a workflow that was ~10-11 gb vram is now 14-15 gb

**Comment by cubiq** [comment] 2023-10-14 14:22
I updated comfyanonymous on the situation, hopefully he'll be able to do something about it

**Comment by Inner-Reflections** [comment] 2023-10-15 00:39
Thanks!

**Comment by cubiq** [comment] 2023-10-18 09:30
please check if the latest version work better especially using the `--disable-smart-memory` option

**Comment by kijai** [comment] 2023-10-18 10:36
I'm not sure this is the cause for this specific memory usage issue people are experiencing, I didn't use IPAdapter before I heard of this issue. But I tested the current versions extensively and noticed that the clip_vision model never gets unloaded, even if you run out of memory. The` --disable-smart-memory` -arg does allow it to be unloaded, freeing up some VRAM for sampling. I also made a node to debug all this (it's in my node pack), which has the option to force unload the clip_vision model specifically, along with the default cuda cache flushing.

**Comment by cubiq** [comment] 2023-10-18 10:40
for AnimateDiff I highly recommend saving the embeds (even if it's just one image) and loading them in the AD workflow with the loadembeds node

**Comment by InB4DevOps** [comment] 2023-10-18 10:44
> for AnimateDiff I highly recommend saving the embeds (even if it's just one image) and loading them in the AD workflow with the loadembeds node

Can you please explain that more precisely?

**Comment by melMass** [comment] 2023-10-18 10:49
> Can you please explain that more precisely?

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/7041726/50086909-b8fa-46eb-a399-f3cd3ddc2f3c)

For me it doesn't change anything, it really seems to be related to the "context" length in animateDiff, like it's ignoring it and batching the total frames

**Comment by kijai** [comment] 2023-10-18 11:32
I suspect  what he means is that if you load the embeds you don't need clip_vision and thus save memory? Personally I see no difference in VRAM usage after those commits (rolled back to test), but I can confirm even before the clip_vision does not get unloaded and you since can run out of memory during sampling it can be enough to cap you.

**Comment by cubiq** [comment] 2023-10-18 11:51
in my tests, on my system, with a 4090, it saves me 1.4Gb or vram. so it's not nothing.

**Comment by kijai** [comment] 2023-10-18 11:58
> in my tests, on my system, with a 4090, it saves me 1.4Gb or vram. so it's not nothing.

Yes this is about what the clip_vision takes, it should be unloaded before sampling but it's not and this memory usage stays: 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/40791699/dde44c6b-9c00-48e8-a486-baee85d97600)

**Comment by InB4DevOps** [comment] 2023-10-18 13:33
Where do I need to put an ipadapter embed file? I tried `custom_nodes\ComfyUI_IPAdapter_plus\models\` and refreshed the page but the file does not show up in the `Load IPAdapter embeds` widget.

**Comment by cubiq** [comment] 2023-10-18 13:33
input/

**Comment by InB4DevOps** [comment] 2023-10-18 13:37
Thanks! This is something I have often wondered - how do I get the path where a node expects its files?

according to this https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/IPAdapterPlus.py#L268C16-L268C16 I would have expected it to be `custom_nodes\ComfyUI_IPAdapter_plus\models\`

**Comment by cubiq** [comment] 2023-10-18 14:55
all input images (masks, img2img, preprocessed, etc...) should go in the input/ directory

**Comment by Inner-Reflections** [comment] 2023-10-19 01:53
Did not change the main issue

**Comment by InB4DevOps** [comment] 2023-10-19 14:51
I was already getting my hopes up as this sounded really promising but

```
    raise RuntimeError("Windows not yet supported for torch.compile")
RuntimeError: Windows not yet supported for torch.compile
```

Guess I'll need to dig out my WSL and try there :)

**Comment by cubiq** [comment] 2023-10-19 14:53
ah that explains why it's not wide spread :smile:

**Comment by InB4DevOps** [comment] 2023-10-19 15:45
I just tried the node on WSL (Ubuntu 22.04, python 3.10.13) and I'm getting this exception when the node is active. Any idea?

```
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/sd/ComfyUI')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sd/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/sd/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/sd/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/sd/ComfyUI/custom_nodes/ComfyUI_essentials/essentials.py", line 423, in execute
    model.model.diffusion_model = torch.compile(model.model.diffusion_model, dynamic=dynamic, fullgraph=fullgraph, mode=mode)
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/__init__.py", line 1723, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 610, in optimize
    compiler_config=backend.get_compiler_config()
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/__init__.py", line 1571, in get_compiler_config
    from torch._inductor.compile_fx import get_patched_config_dict
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 38, in <module>
    from .fx_passes.joint_graph import joint_graph_passes
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/fx_passes/joint_graph.py", line 8, in <module>
    from ..pattern_matcher import (
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/pattern_matcher.py", line 28, in <module>
    from .lowering import fallback_node_due_to_unsupported_type
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 4768, in <module>
    import_submodule(kernel)
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1492, in import_submodule
    importlib.import_module(f"{mod.__name__}.{filename[:-3]}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/kernel/bmm.py", line 4, in <module>
    from ..select_algorithm import (
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 25, in <module>
    from .codegen.triton import texpr, TritonKernel, TritonPrinter, TritonScheduling
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/codegen/triton.py", line 26, in <module>
    from ..triton_heuristics import AutotuneHint
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/triton_heuristics.py", line 23, in <module>
    from .coordinate_descent_tuner import CoordescTuner
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/coordinate_descent_tuner.py", line 8, in <module>
    if has_triton():
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/torch/_inductor/utils.py", line 83, in has_triton
    import triton
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/triton/__init__.py", line 8, in <module>
    from .runtime import (
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune,
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 8, in <module>
    from .jit import KernelInterface
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/triton/runtime/jit.py", line 14, in <module>
    from ..common.backend import get_backend, path_to_ptxas
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/triton/common/__init__.py", line 1, in <module>
    from .build import _build, cuda_include_dir, libcuda_dirs
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/triton/common/build.py", line 10, in <module>
    import setuptools
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    ws = cls()
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 565, in __init__
    self.add_entry(entry)
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1988, in find_distributions
    importer = get_importer(path_item)
  File "/usr/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'

Prompt executed in 0.17 seconds
```

**Comment by cubiq** [comment] 2023-10-19 15:51
are you using the right environment? that's an odd error message to get

**Comment by InB4DevOps** [comment] 2023-10-19 16:57
> are you using the right environment? that's an odd error message to get

Yeah, same venv I use for comfyui which which works with the node when bypassed.

**Comment by filliptm** [comment] 2023-10-20 05:57
> I made a few tests by compiling the model and the results are promising.
> 
> I have an animation with controlnet + ipadapter at 768x512, 32 frames. Normally it takes 21gb of VRAM, with compile the same scene takes 10gb (!!!)
> 
> ```
> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
> |-----------------------------------------+----------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
> |                                         |                      |               MIG M. |
> |=========================================+======================+======================|
> |   0  NVIDIA GeForce RTX 4090        Off | 00000000:08:00.0  On |                  Off |
> | 45%   72C    P2             434W / 450W |  10410MiB / 24564MiB |    100%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
> ```
> 
> The caveat is that the model compilation takes 3-10 minutes depending on the machine.
> 
> I'd like you guys to try. I created a very beta node you can download here https://github.com/cubiq/ComfyUI_essentials
> 
> The node is called "ModelCompile". Add it as very last step before the KSampler like so:
> 
> ![image](https://user-images.githubusercontent.com/427614/276642371-589ba901-fc86-4e33-8d4b-7c59f910d31e.png)
> 
> **IMPORTANT:**
> 
> 1. Use the default values
> 2. the first time you run the workflow it will take some time to compile the model. On my system it takes about 3 minutes
> 3. Once compiled you can't change anything in the workflow (apart from a few parameters like the seed). **If you need to change anything you must stop the server and rerun it.**
> 4. The actual image generation is **twice as fast** and takes **half the vram** on my system.
> 5. I'm not sure if it's only a 4090 thing (and no benefit would be appreciable with smaller cards)
> 6. update: apparently only works on Linux

This seems to be a work around solution dont you think? 10gb of Vram seems pretty extreme of a jump up simply by using the node

tho compiling it may work, the time it takes on initial startup is kinda ridiculous and is borderline deterring for anyone who actually wants to use the node

**Comment by cubiq** [comment] 2023-10-20 06:10
I don not agree @filliptm . First of all 3 minutes to compile (only the first time) is not that much in the grand scheme of an animatediff animation, but most importantly the memory consumption difference is so important that can't be ignored. It can make the difference between being able and not being able to do the animation (or add more controlnets, frames, up the resolution, etc...). So if the alternative is NOT using animatediff or using it at a very low resolution, well I guess 3 minutes are acceptable.

Unfortunately unless comfyui changes something in memory management there's nothing I can do about it. Of course one could try to use [animatediff-cli](https://github.com/neggles/animatediff-cli).

**Comment by melMass** [comment] 2023-10-20 09:39
@cubiq do you know the culprit commit in the end? I personally will just revert back to how it was last week, since it worked perfectly fine for my needs (I use windows and macOS so no torch.compile)

**Comment by cubiq** [comment] 2023-10-20 10:08
@melMass unfortunately I don't know when this started exactly, but torch compile works on mac (if you have the right environment)

**Comment by melMass** [comment] 2023-10-20 10:45
Good to know thanks! Well I'll be the guinea pig. I'll report here if I find the culprit commit on ComfyUI

**Comment by filliptm** [comment] 2023-10-20 10:55
> Good to know thanks! Well I'll be the guinea pig. I'll report here if I find the culprit commit on ComfyUI. I have a workflow that I know worked last week so it should serve as some reference

I found one that works, running IPA - 3 control nets = 14gb

4f64fda

**Comment by cubiq** [comment] 2023-10-20 11:03
are you using the plus model with multiple input images?

**Comment by filliptm** [comment] 2023-10-20 11:07
> are you using the plus model with multiple input images?

confirmed working with plus and multiple images

**Comment by cubiq** [comment] 2023-10-20 11:14
the commit from Sep 27 is an important one and you should not revert prior to that. each image added to the plus model is pretty expensive so to keep the memory down you should try to limit the number of images.

I can try to work on a way lo lower memory usage as much as possible on the ipadapter side of things but we are reaching the limit of what the model can do

**Comment by kijai** [comment] 2023-10-20 11:39
I can confirm that rolling back to https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/4f64fda08922f11f5ffc5f8084be32711b4c7833
reduces memory usage by 3GB for me. Also unloading clip_vision further reduces memory usage on this commit as well.

**Comment by kijai** [comment] 2023-10-20 12:48
I further added commit by commit, and concluded that this one https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/a4840bb47f521153a205bef6d7ea0db587358b9d
increases my VRAM usage by 4-5GB

**Comment by cubiq** [comment] 2023-10-20 12:57
there was a bug that basically prevented the uncond images to be loaded for the plus model if more than 1 reference was used. it is using less memory because it is not actually loading all the features of the images over the 1st one. It's not something we can revert to

**Comment by kijai** [comment] 2023-10-20 13:16
> there was a bug that basically prevented the uncond images to be loaded for the plus model if more than 1 reference was used. it is using less memory because it is not actually loading all the features of the images over the 1st one. It's not something we can revert to

All it takes to reduce memory usage is to do "del frame" at the end of the function.

**Comment by cubiq** [comment] 2023-10-20 13:21
I wanted to rewrite the attention thing anyway. I'm working on it, I sweat :smile:

**Comment by cubiq** [comment] 2023-10-20 13:43
I've put a patch to this until I find a better solution

**Comment by Inner-Reflections** [comment] 2023-10-20 13:48
It works!

**Comment by Inner-Reflections** [comment] 2023-10-20 14:08
Ip adpater plus is broken now though 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/147873716/e17de343-f70c-41cc-ab8a-5a4828217aa5)

**Comment by cubiq** [comment] 2023-10-20 14:13
I can't replicate, please share your workflow and your initial comfyui message

**Comment by Inner-Reflections** [comment] 2023-10-20 14:23
Here
[Error Workflow IP.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13055241/Error.Workflow.IP.json)

**Comment by Inner-Reflections** [comment] 2023-10-20 14:24
The XL IPadpaters work fine (in fact the SDXL (not vit) one is actually better than ever for VRAM usage) just IP adapter plus and plus face.

**Comment by Inner-Reflections** [comment] 2023-10-20 14:40
That's somthing I do not know how to do - as it stand it does not bother me. But I have informed [kijai](https://github.com/kijai) who found this bug

**Comment by cubiq** [comment] 2023-10-20 14:43
> That's somthing I do not know how to do - as it stand it does not bother me. But I have informed [kijai](https://github.com/kijai) who found this bug

please try the new update I just pushed

**Comment by cubiq** [comment] 2023-10-20 15:08
just for future reference the error is caused by a previous version of `transformers`, anyway it's fixed now

**Comment by Inner-Reflections** [comment] 2023-10-20 15:49
Thanks!

**Closed** 2023-10-20 15:51 UTC

**Comment by InB4DevOps** [comment] 2023-10-20 19:47
> > Yeah, same venv I use for comfyui which works with the node when bypassed.
> 
> there seems to be a problem with your environment as at the top it tries to load from the global python install `/usr/lib/python3.10/` but later from the local one `/home/sd/ComfyUI/venv/lib/python3.10/site-packages/`
> 
> It seems you are working on a mixed environment (are you activating the environment before running comfy?)

Ok, so I tried it all. `virtualenv`, `python3 -m venv venv` and only when I used `pyenv` I did not get that odd thing where python from inside the venv would use `/usr/lib/python3.10/pkgutil.py`. The error however remained: 
```
File "/home/sd/ComfyUI/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1988, in find_distributions
    importer = get_importer(path_item)
```

The fix for this I found here: https://github.com/n1ngu/faker/commit/6e36d1791e70b72a2ae779aa3175c13d4babe582

I then had to change this file: `home/sd/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pkg_resources/__init__.py` and replace two occurences of `get_importer(path_item)` to `get_importer(str(path_item))`.

I have no idea why this problem exists but this fixed it for me.
