### ISSUE TITLE
Error occurred when executing IPAdapter: insightface model is required for FaceID models

### ISSUE THREAD

**Issue by a-niess** [cubiq/ComfyUI_IPAdapter_plus#401] opened 2024-04-05 23:59 UTC
I have installed all the models, FaceID, LoRAs, etc. in the proper directories per the [Installation](https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/README.md#installation) instructions. I am only working with SDXL and have omitted the SD1.5 installations.

I have also installed insightface via `pip install insightface`
and onnxruntime via `pip install onnxruntime` and `pip install onnxruntime-gpu` within the `/workspace/ComfyUI` directory. I am running ComfyUI via RunPod with the `ComfyUI - Jupyter` template.

<img width="763" alt="Screenshot 2024-04-05 at 6 52 48 PM" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135653878/5bb46234-1265-44a4-af7e-13c315c52ff1">

I appreciate any help others may be able to offer on this error:

```
Error occurred when executing IPAdapter:

insightface model is required for FaceID models

File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 569, in apply_ipadapter
return (ipadapter_execute(model.clone(), ipadapter['ipadapter']['model'], ipadapter['clipvision']['model'], **ipa_args), )
File "/workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 181, in ipadapter_execute
raise Exception("insightface model is required for FaceID models")
```

**Comment by a-niess** [comment] 2024-04-06 00:03
The error is defined in `ComfyUI_IPAdapter_plus/IPAdapterPlus.py` [here](https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/IPAdapterPlus.py) in lines 180–181:
 
'''
 if is_faceid and not insightface:
        raise Exception("insightface model is required for FaceID models")
'''

**Comment by TrickleDownClown** [comment] 2024-04-06 06:55
I continue to have this same issue.  Even after all the suggested fixes (#162) I am unsure how to proceed.

**Comment by cubiq** [comment] 2024-04-06 07:05
FaceID models require the FaceID IPadapter node. You are probably just using the wrong node

**Comment by deniansouza** [comment] 2024-04-06 18:26
The exact same thing happend to me. Turns out I just needed to restart ComfyUI (I had installed everything while it was running).

**Comment by TrickleDownClown** [comment] 2024-04-06 20:53
> FaceID models require the FaceID IPadapter node. You are probably just using the wrong node

I double checked and I am using that node.  It seems the install of Insight is missing but it's installed, the appears to be correct and I used the onnxruntime to add to the wheel. as per the #162

**Comment by cubiq** [comment] 2024-04-07 06:08
do you get any error at startup

**Comment by Anti-Liang** [comment] 2024-04-09 07:20
In my case, download InsightFace model will solve this problem.

**Comment by Noctropolitan** [comment] 2024-04-13 13:23
I'm having exactly the same error. Any ideas?

**Comment by cubiq** [comment] 2024-04-16 16:34
I'm closing this as it looks like a configuration issue and not a bug

**Closed by cubiq** 2024-04-16 16:34 UTC

**Comment by a-niess** [comment] 2024-04-16 16:51
The errors I get in my RunPod environment are resolved by using the ComfyUI Manager `Install PIP packages` button and completing the following installations:

`pip install pillow==10.2.0`
`pip install insightface`
`pip install onnxruntime`
`pip install onnxruntime-gpu`

Afterward, I do not get any issues.

**Comment by philcoraz** [comment] 2024-04-20 13:22
At [a-niess](https://github.com/a-niess)  it worked thx a lot

**Comment by a-niess** [comment] 2024-04-20 16:34
@philcoraz I'm glad it worked for you! There's a way to configure your RunPod so that these installations will persist in your python virtual environment, but doing the installs through the ComfyUI Manager each time is pretty straightforward.

**Comment by jgal14** [comment] 2024-04-25 17:16
@a-niess could you confirm which RunPod template you are using please? The install pip packages approach is giving me this error;

Failed to install 'pip install pillow==10.2.0 insightface onnxruntime onnxruntime-gpu'
See terminal log.

**Comment by a-niess** [comment] 2024-04-25 17:22
@jgal14 I am using the `ghcr.io/ai-dock/comfyui:latest-jupyter` template. The template used to be offered by default on RunPod but was removed some time around last week. If this is the template you are using, the closest equivalent is `ghcr.io/ai-dock/comfyui:latest` so you can just edit the template by appending `-jupyter` to the end of the title for the  Container Image and then confirm with "Set Overrides." I am also using a network volume.

**Comment by jgal14** [comment] 2024-04-25 17:26
> @jgal14 I am using the `ghcr.io/ai-dock/comfyui:latest-jupyter` template. The template used to be offered by default on RunPod but was removed some time around last week. If this is the template you are using, the closest equivalent is `ghcr.io/ai-dock/comfyui:latest` which RunPod calls `ComfyUI - AI-Dock`, so you can just edit the template by appending `-jupyter` to the end of the title for the Container Image and then confirm with "Set Overrides." I am also using a network volume.

Awesome thanks! I'll check this out.

**Comment by jgal14** [comment] 2024-04-25 18:06
@a-niess I set that template up and opened the port and it's asking for a login. Where do I create these credentials?

**Comment by jgal14** [comment] 2024-04-25 18:11
scratch that, found it!

**Comment by a-niess** [comment] 2024-04-25 18:11
@jgal14 The default with this container image is

`user`
`password`

and can be configured to something else.

**Comment by jgal14** [comment] 2024-04-25 18:12
> @jgal14 The default with this container image is
> 
> `user` `password`
> 
> and can be configured to something else.

Thank you again

**Comment by jgal14** [comment] 2024-04-25 20:00
@a-niess did you use a custom image to get the IP-adapter running on this template? Models I'm adding to the standard file structure aren't showing in workflows!

**Comment by a-niess** [comment] 2024-04-25 21:54
@jgal14 When you connect to the Jupyter notebook via `Connect to HTTP Service [Port 1111]`: 

1. launch a new terminal
2. `cd` into the appropriate directory for where you want to add models. E.g., if you're adding a LoRA then `cd ComfyUI/models/loras` 
3. copy the download URL of the model from its source. E.g., if on CivitAI or HF, copy the right-click on the download button/link for the model, then copy link address
4. back in the jupyter notebook terminal once you are in the appropriate directory from step 1, `wget paste-model-URL` E.g. `wget https://civitai.com/api/download/models/135867` will download the file `add-detail-xl.safetensors` from the [Detail Tweaker XL](https://civitai.com/models/122359?modelVersionId=135867) page on CivitAI.
5. In some cases, the model will only download as `135867` without a `.ckpt` or `.safetensors` extension. In that case, rename the file with the extension so that it will appear in your ComfyUI nodes. To do so in the same terminal and directory, `mv current-name target-name` E.g. `mv 135867 add-detail-xl.safetensors`

Note: You can always use `ls` to see the contents of the current directory (not sure how familiar you may be with command line.

**Comment by jgal14** [comment] 2024-04-26 09:27
> @jgal14 When you connect to the Jupyter notebook via `Connect to HTTP Service [Port 8888]`:
> 
> 1. launch a new terminal
> 2. `cd` into the appropriate directory for where you want to add models.
>    E.g., if you're adding a LoRA then `cd ComfyUI/models/loras`
> 3. copy the download URL of the model from its source. E.g., if on CivitAI or HF, copy the right-click on the download button/link for the model, then copy link address
> 4. back in the jupyter notebook terminal once you are in the appropriate directory from step 1,
>    `wget paste-model-URL`
>    E.g. `wget https://civitai.com/api/download/models/135867` will download the file `add-detail-xl.safetensors` from the [Detail Tweaker XL](https://civitai.com/models/122359?modelVersionId=135867) page on CivitAI.
> 5. In some cases, the model will only download as `135867` without a `.ckpt` or `.safetensors` extension. In that case, rename the file with the extension so that it will appear in your ComfyUI nodes. To do so in the same terminal and directory,
>    `mv current-name target-name`
>    E.g. `mv 135867 add-detail-xl.safetensors`
> 
> Note: You can always use `ls` to see the contents of the current directory (not sure how familiar you may be with command line.
> 
> Models installed as above will only persist if you are using a network volume in RunPod. If you are not using a network volume (found under RunPod's Storage tab on the left), then these models will not be there next time you spin up your pod.

Awesome thank you for the detailed response, this is up and running now.

Now, onto a serverless deployment!

**Comment by heytony965342** [comment] 2024-10-13 15:18
Download the/buffalo_1. zip file again, https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip Copy to the \ ComfyUI \ models \ insightface \ models directory and unzip

**Comment by yuzzi1962** [comment] 2025-08-08 12:29
I had the same issue on my desktop where I was building a project on Windows 11.
You need to install the Microsoft Visual C++ 14.0 or later. Download it using the Microsoft Visual Studio installer:
https://visualstudio.microsoft.com/visual-cpp-build-tools/
Select: Workloads → Desktop development with C++
Individual Components must be checked:
Windows SDK
C++ x64/x86 build tools
and then click the Install button
After that you can install insightface properly:
python -m pip install insightface

**Comment by JaironAmorim** [comment] 2025-12-25 22:31
> I had the same issue on my desktop where I was building a project on Windows 11. You need to install the Microsoft Visual C++ 14.0 or later. Download it using the Microsoft Visual Studio installer: https://visualstudio.microsoft.com/visual-cpp-build-tools/ Select: Workloads → Desktop development with C++ Individual Components must be checked: Windows SDK C++ x64/x86 build tools and then click the Install button After that you can install insightface properly: python -m pip install insightface

This worked for me, thank you.
